import pygame as pg

spritesheets = {
    "field":pg.image.load("assets/textures/FieldsTileset.png")
}

tile_textures = {
    "grass":{
        "source":spritesheets['field'],
        "row":4,
        "column":5,
        "tile_size":32
    },
    "stone_topleft":{
        "source":spritesheets['field'],
        "row":0,
        "column":5,
        "tile_size":32
    },
    "stone_top":{
        "source":spritesheets['field'],
        "row":0,
        "column":6,
        "tile_size":32
    },
    "stone_topright":{
        "source":spritesheets['field'],
        "row":0,
        "column":7,
        "tile_size":32
    },
    "stone_left":{
        "source":spritesheets['field'],
        "row":1,
        "column":5,
        "tile_size":32
    },
    "stone_center":{
        "source":spritesheets['field'],
        "row":2,
        "column":2,
        "tile_size":32
    },
    "stone_right":{
        "source":spritesheets['field'],
        "row":1,
        "column":7,
        "tile_size":32
    },
    "stone_bottomleft":{
        "source":spritesheets['field'],
        "row":2,
        "column":5,
        "tile_size":32
    },
    "stone_bottom":{
        "source":spritesheets['field'],
        "row":2,
        "column":6,
        "tile_size":32
    },
    "stone_bottomright":{
        "source":spritesheets['field'],
        "row":2,
        "column":7,
        "tile_size":32
    },
}